/*
 * @author Fedmich <fedmich@gmail.com>
 * @license All Rights Reserved
 * @copyright (C) 2014 Fedmich.  All rights reserved.
 *
 * THIS APP WAS SECURELY PACKAGED BY FEDMICH http://fedmich.com/go/chrome_packager/
 */
/*
All Rights Reserved
@site http://pagexray.com/about/

@stats 319 patterns
@last_updated May 22, 2014
 */
var px_ptn = {
	"ad-adroll": {
		pattern: [/\/\/s.adroll.com/i, /\/\/a.adroll.com/i],
		name: "AdRoll ads"
	},
	"ad-bidvertiser": {
		pattern: [/\/\/srv.bidvertiser.com\/bidvertiser\//i, /\/\/bdv.bidvertiser.com\/BidVertiser.dbm/i],
		name: "BidVertiser Ads"
	},
	adbrite: {
		pattern: [/adbrite.com\/adserver\//i, /.adbrite.com\/mb\//i],
		name: "adBrite Exchange ads"
	},
	adbsa: {
		pattern: [/\/\/s3.buysellads.com/i],
		name: "Buy Sell Ads"
	},
	"ad-clickbank": {
		pattern: [/\/\/lefthd.hopfeed.com\/script\//i],
		name: "Clickbank ads"
	},
	"ad-doubleclick": {
		pattern: [/\/\/ad.doubleclick.net\/adj\//i,
			/\/\/ad.doubleclick.net\/ad\//i],
		name: "DoubleClick"
	},
	"ad-matomymedia": {
		pattern: [/\/\/ad.xtendmedia.com\/st/i],
		name: "Matomy Media ads"
	},
	adopenx: {
		pattern: [/https:\/\/d\d.openx.org\/ajs.php/i, /\x3c!-- Generated by OpenX/i, /\x3c!--\/* OpenX Javascript Tag/i, /\x3c!--\/* OpenX iFrame Tag/i, /\/delivery\/ajs.php\'/i],
		name: "OpenX ads"
	},
	"ad-po-st": {
		pattern: [/\/\/i.po.st\/share\/script\/post-widget.js/i, /\x3c!-- Begin Po.st Tag --\x3e/i],
		name: "Po.st"
	},
	adpw: {
		pattern: [/\/\/www.projectwonderful.com\/ad_display.js/i],
		name: "Project Wonderful Ads"
	},
	adsense: {
		pattern: [/\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js/i, /GS_googleAddAdSenseService\(/i],
		name: "Adsense"
	},
	"ads-infolinks": {
		pattern: [/http:\/\/resources.infolinks.com\/js\/infolinks_main.js/i],
		name: "infolinks ads"
	},
	linkbucks: {
		pattern: [/http:\/\/.*.linkbucks.com\/url\//i, /\/\/www.linkbucks.com\/Webservices\/jsParseLinks.aspx/i],
		name: "Linkbucks ads"
	},
	cms_drupal: {
		pattern: [/jQuery.extend\(Drupal.settings,/i],
		name: "Drupal CMS"
	},
	cms_joomla: {
		pattern: [/<meta name="generator" content="Joomla!/i,
			/\/css\/joomla.css"/i, /Powered by <a .*>Joomla!<\/a>/i, /Joomla SEO powered by JoomSEF/i, /index.php\?option=com_content/i],
		name: "Joomla!"
	},
	cms_silverstripe: {
		pattern: [/<meta name="generator" content="SilverStripe/i],
		name: "SilverStripe CMS"
	},
	cms_sitefinity: {
		pattern: [/<meta name="Generator" content="Sitefinity (.*)"/i],
		name: "Sitefinity CMS"
	},
	cms_textpattern: {
		pattern: [/textpattern\/css/i, /powered by <a href="http:\/\/textpattern.com"/i],
		name: "TextPattern CMS"
	},
	cms_typo: {
		pattern: [/<meta name="generator" content="TYPO3/i],
		name: "Typo CMS"
	},
	cms_webgui: {
		pattern: [/<meta name="generator" content="WebGUI (.*)"/i],
		name: "WebGUI CMS"
	},
	cms_xoops: {
		pattern: [/<meta name="generator" content="XOOPS/i],
		name: "XOOPS CMS"
	},
	"cms-alfresco": {
		pattern: [/alfresco-min.*.js/i],
		name: "Alfresco"
	},
	"cms-avactis": {
		pattern: [/<meta name="author" content="Avactis Team/i, /\/avactis-themes\//i],
		name: "Avactis CMS"
	},
	"cms-berta": {
		pattern: [/var bertaGlobalOptions/i],
		name: "Berta CMS"
	},
	"cms-bitrix": {
		pattern: [/<link href="\/bitrix\//i],
		name: "Bitrix - CMS"
	},
	"cms-browsercms": {
		pattern: [/<meta name="generator" content="BrowserCMS/i],
		name: "BrowserCMS - (Ruby on Rails)"
	},
	"cms-concrete5": {
		pattern: [/<meta name="generator" content="concrete5/i],
		name: "concrete5 CMS"
	},
	"cms-contenido": {
		pattern: [/<meta name="generator" content="CMS Contenido/i],
		name: "Contenido CMS"
	},
	"cms-cotonti": {
		pattern: [/<meta name="generator" content="Cotonti/i],
		name: "CotontiCMS"
	},
	"cms-data-life": {
		pattern: [/<meta name="generator" content="DataLife Engine/i],
		name: "DataLife Engine CMS"
	},
	"cms-dragonfly": {
		pattern: [/<meta name="generator" content="CPG Dragonfly CMS/i],
		name: "CPG Dragonfly CMS"
	},
	"cms-episerver": {
		pattern: [/<meta name="GENERATOR" content="EPiServer/i],
		name: "EPiServer CMS"
	},
	"cms-expressionengine": {
		pattern: [/SERVER INFO:.*Set-Cookie: exp_last_visit/i],
		name: "Expression Engine"
	},
	"cms-ez_publish": {
		pattern: [/<meta name="generator" content="eZ Publish/i],
		name: "ez Publish CMS"
	},
	"cms-fuel": {
		pattern: [/\.css\?c=/i, /\.js\?c=/i, /SERVER INFO:.*Set-Cookie: .*%22fuel_/i, /SERVER INFO:FUEL_CMS/i],
		name: "Fuel CMS"
	},
	"cms-getsimple": {
		pattern: [/<meta name="generator" content="GetSimple/i],
		name: "GetSimple CMS"
	},
	"cms-impresspages": {
		pattern: [/<meta name="generator" content="ImpressPages CMS/i],
		name: "ImpressPages CMS"
	},
	"cms-koobi": {
		pattern: [/<meta name="generator" content="\(c\) Koobi/i, /<meta name="generator" content="Koobi/i],
		name: "Koobi CMS"
	},
	"cms-modx": {
		pattern: [/\/min\/b=.*&f=.*/i, /modx_MEDIA_PATH/i],
		name: "MODX cms"
	},
	"cms-nucleus": {
		pattern: [/<meta name="generator" content="Nucleus/i],
		name: "Nucleus CMS"
	},
	"cms-orchard": {
		pattern: [/<meta content="Orchard" name="generator" \/>/i],
		name: "Orchard CMS"
	},
	"cms-percussion": {
		pattern: [/<meta content="Percussion Rhythmyx" name="generator">/i, /<meta content="Percussion CM System" name="generator"\/>/i],
		name: "Percussion Rhythmyx/CMS System"
	},
	"cms-plone": {
		pattern: [/<meta name="generator" content="Plone/i],
		name: "Plone CMS"
	},
	"cms-serendipity": {
		pattern: [/<meta name="Powered-By" content="Serendipity/i],
		name: "Serendipity Weblog"
	},
	"cms-umbraco": {
		pattern: [/\/umbraco\//i],
		name: "Umbraco"
	},
	"cms-webnode": {
		pattern: [/<meta name="generator" content="Webnode/i],
		name: "Webnode CMS"
	},
	jobberbase: {
		pattern: [/<meta name="generator" content="Jobberbase/i, /Jobber.PerformSearch\(\'/i],
		name: "jobberBase Job Board"
	},
	octopress: {
		pattern: [/<span class="credit">Powered by <a href="http:\/\/octopress.org">Octopress<\/a><\/span>/i],
		name: "Octopress framework"
	},
	phplinkdirectory: {
		pattern: [/<meta name="generator" content="PHP Link Directory/i],
		name: "PHP Link Directory"
	},
	wordpress: {
		pattern: [/<meta.*\?name="generator" content="WordPress (.*)"/i, /<meta.*name="generator" content="WordPress/i, /\/wp-content\/(includes|plugins|themes)/i,
			/\/wp-content\/themes\/.*css/i, /optimized with the Yoast WordPress/i],
		name: "WordPress Blog/CMS"
	},
	fontdeck: {
		pattern: [/f.fontdeck.com\/s\/css\//i, /WebFontConfig = { fontdeck:/i],
		name: "Fontdeck web fonts"
	},
	fortawesome: {
		pattern: [/font-family: \'FontAwesome\';/i],
		name: "Font Awesome CSS Design tool"
	},
	oscommerce: {
		pattern: [/\/store\/product_info.php\?products_id/i, /\/index.php\?main_page=product_info&/i, /_eof \/\/--\x3e/i],
		name: "osCommerce"
	},
	"prestashop-ecommerce": {
		pattern: [/<meta name="generator" content="PrestaShop/i],
		name: "PrestaShop"
	},
	"shopify-ecommerce": {
		pattern: [/This store is powered by Shopify/i, /<link href=".*\/\/cdn.shopify.com/i],
		name: "Shopify ecommerce"
	},
	"shopware-ecommerce": {
		pattern: [/\/shopware.php\/sViewport,account/i, /\/engine\/shopware\/Plugins\//i],
		name: "Shopware AG ecommerce"
	},
	"zencart-ecommerce": {
		pattern: [/<meta name="generator" content="shopping cart program by Zen Cart/i, /<meta name="generator" content="Zen Cart/i],
		name: "ZenCart eCommerce Shopping cart"
	},
	forum_phpbb: {
		pattern: [/<meta name="copyright" content="\d\d\d\d-\d\d\d\d phpBB Group/i,
			/NOTE: This page was generated by phpBB,/i, /Powered by phpBB/i],
		name: "phpbb forum"
	},
	forum_simplemachines: {
		pattern: [/Powered by SMF /i],
		name: "Simple Machines Forum"
	},
	forum_vbulletin: {
		pattern: [/<meta name="generator" content="vBulletin/i, /Powered by vBulletin&reg;/i, / id="vbulletinlink"/i],
		name: "vBulletin Forum"
	},
	"forum-bbPress": {
		pattern: [/<meta name="generator" content="bbPress/i, /<body class="forum-archive bbPress/i],
		name: "bbPress Forum"
	},
	"forum-discuz": {
		pattern: [/<meta name="generator" content="Discuz!/i],
		name: "Discuz Forum"
	},
	"forum-ipboard": {
		pattern: [/Community Forum Software by Invision Power Services/i, /<body id=\'ipboard_body/i, /\/ipb_print.css/i, /ipb.vars\[/i],
		name: "Invision Power Board Forum (IP Board)"
	},
	"forum-liferay": {
		pattern: [/liferay={Browser:/i],
		name: "LifeRay Portal/Forum"
	},
	"forum-mybb": {
		pattern: [/Powered By <a .*>MyBB<\/a>/i, /MyBB.changeLanguage();/i],
		name: "MyBB Forum"
	},
	"forum-phpnuke": {
		pattern: [/<META NAME="GENERATOR" CONTENT="PHP-Nuke/i],
		name: "PHP Nuke Forum"
	},
	"forum-vanilla": {
		pattern: [/\/vanilla\/js\/discussion.js/i,
			/\/vanilla\/js\/options.min.js/i],
		name: "Vanilla Forums Community"
	},
	"forum-xenforo": {
		pattern: [/Forum software by XenForo/i],
		name: "XenForo Forum"
	},
	"forum-yetanotherforum-yafnet": {
		pattern: [/yaf.controls./i, /function yaf_GetForm()/i, /Forum powered by <a .*>Yet Another Forum.net<\/a>/i],
		name: "YAF.NET Forum"
	},
	"code-igniter": {
		pattern: [/Set-Cookie: ci_session=/i],
		name: "Code Igniter"
	},
	coldfusion: {
		pattern: [/\/CFIDE\/scripts\/cfform.js/i, /href=".*.cfm"/i],
		name: "ColdFusion Server (CFM)"
	},
	"django-web-framework": {
		pattern: [/<div id="footer">.*powered by Django.*<\/div>/i],
		name: "Django Web Framework (Python)"
	},
	"grid-960": {
		pattern: [/\/960.css/i],
		name: "960 Grid System"
	},
	"html-kickstart": {
		pattern: [/\/kickstart.css/i, /\/kickstart.js/i],
		name: "HTML KickStart"
	},
	"jquery-mobile": {
		pattern: [/\/jquery.mobile-/i],
		name: "jQuery Mobile"
	},
	php_cakephp: {
		pattern: [/http:\/\/book.cakephp.org\/img\/cake.power.gif/i, / powered by CakePhp<\/a>/i, /Powered by <a href="http:\/\/cakephp.org"/i, /SERVER INFO:.*CAKE_PHP/i, /SERVER INFO:.*Set-Cookie: CAKEPHP=/i],
		name: "Cake PHP"
	},
	"twitter-bootstrap": {
		pattern: [/\/bootstrap-.*\.js/i,
			/\/bootstrap.css/i, /bootstrap.min.js/i, /Made with <a .*href="http:\/\/getbootstrap.com">Bootstrap.*<\/a>/i, /\/bootstrap.js/i],
		name: "Twitter's Bootstrap"
	},
	"yii-framework": {
		pattern: [/YII_CSRF_TOKEN=\'/i, /Set-Cookie: YII_CSRF_TOKEN=/i],
		name: "Yii Framework"
	},
	"imghost-photobucket": {
		pattern: [/.photobucket.com\/albums\//i],
		name: "photobucket images"
	},
	"jquery_chili_code-highlight": {
		pattern: [/\/jquery.chili./i, /\/jquery.chili-/i],
		name: "jQuery Chili"
	},
	jquery_easing: {
		pattern: [/\/jquery.easing./i, /\/jquery.easing-/i],
		name: "jQuery Easing Plugin"
	},
	jquery_jatt: {
		pattern: [/\/jquery.jatt.min.js/i, /\/jquery.jatt.js/i],
		name: "Jatt - just another tooltip"
	},
	jquery_mentions: {
		pattern: [/jquery.mentionsInput.css/i, /jquery.mentionsInput.js/i, /mentions-style.css/i],
		name: "jQuery mentionsInput"
	},
	jquery_plug_AnythingSlider: {
		pattern: [/\/jquery.anythingslider.min.js/i, /\/jquery.anythingslider.js/i],
		name: "AnythingSlider jQuery Plugin"
	},
	jquery_plug_cookie: {
		pattern: [/\/jquery.cookie/i],
		name: "jQuery Cookie plugin"
	},
	jquery_plug_cycle: {
		pattern: [/jquery.cycle.all.min.js/i,
			/\/jquery.cycle.all.js/i],
		name: "jQuery Cycle Plugin"
	},
	jquery_plug_GalleryView: {
		pattern: [/\/jquery.galleryview-/i],
		name: "jQuery GalleryView plugin"
	},
	jquery_plug_growl: {
		pattern: [/\/jquery.jgrowl.css/i, /jquery.growl/i],
		name: "jQuery growl plugin"
	},
	jquery_plug_hoverIntent: {
		pattern: [/jquery.hoverIntent.js/i],
		name: "jQuery hoverIntent plugin"
	},
	jquery_plug_isotope: {
		pattern: [/jquery.isotope.min.js/i],
		name: "jQuery Isotope",
		js_obj: "window.jQuery.Isotope"
	},
	jquery_plug_spritely: {
		pattern: [/\/jquery.spritely/i],
		name: "jQuery spritely plugin"
	},
	jquery_plug_timers: {
		pattern: [/\/jquery.timers-/i],
		name: "jQuery timers"
	},
	jquery_roundabout: {
		pattern: [/\/jquery.roundabout.js/i, /\/jquery.roundabout2.js/i],
		name: "jQuery Roundabout"
	},
	"jquery-masonry": {
		pattern: [/jquery.masonry./i, /masonry-brick"/i],
		name: "jQuery Masonry"
	},
	"jQuery-nyroModal": {
		pattern: [/nyromodal\.(css|js)/i, /\/nyroModal./i],
		name: "NyroModal - jQuery Plugin"
	},
	jqueryui: {
		pattern: [/jquery.ui./i, /\/jqueryui\//i],
		name: "jQuery UI"
	},
	php: {
		pattern: [/<meta name="generator" content="PHP"/i],
		name: "PHP Programming Language"
	},
	feedburner: {
		pattern: [/feeds2.feedburner.com\/~fc\//i, /\/\/feedburner.google.com\/fb\/a\/mailverify/i, /\/\/www.feedburner.com\/fb\/a\/emailverifySubmit/i],
		name: "FeedBurner - Email Subscription / RSS feeds"
	},
	getresponse: {
		pattern: [/<form id="GRSubscribeForm"/i, /action="http:\/\/www.getresponse.com\/cgi-bin\/add.cgi"/i],
		name: "GetResponse - Email marketing"
	},
	infusionsoft: {
		pattern: [/infusionsoft.com\/app\//i, /infusionsoft.com\/AddForms/i],
		name: "Infusionsoft"
	},
	"mail-aweber": {
		pattern: [/\/\/forms.aweber.com\/form\/displays.htm/i,
			/\/\/forms.aweber.com\/form\//i, /aweber.com\/scripts\/addlead.pl/i],
		name: "Aweber Communication - Email marketing"
	},
	mailchimp: {
		pattern: [/\/\/downloads.mailchimp.com\/js\/jquery.form-n-validate.js/i, /\x3c!-- Begin MailChimp Signup Form --\x3e/i, /list-manage.com\/subscribe\//i],
		name: "Mail Chimp email newsletter"
	},
	"google-maps": {
		pattern: [/\/\/maps.google.com\/maps/i, /\/\/maps.google.com\/maps\?/i, /\/\/maps.google.com\/maps\/api\/staticmap/i, /var gmap =/i, /new GMap2\(/i, /google.load\("maps"/i, /\/\/maps.googleapis.com\/maps/i,
			/\/\/ Google Maps object/i],
		name: "Google Maps API / Static Maps"
	},
	maps_gotheresg: {
		pattern: [/"http:\/\/www.gothere.sg\/jsapi/i],
		name: "GoThere.sg Singapore map"
	},
	maps_openlayers: {
		pattern: [/Openlayers./i, /OpenLayers./i],
		name: "OpenLayers Map"
	},
	"maps-kartograph": {
		pattern: [/\/kartograph.js/i],
		name: "Kartograph SVG Map"
	},
	"facebook-videos": {
		pattern: [/\/\/www.facebook.com\/v\//i],
		name: "Facebook Video embeds"
	},
	flowplayer: {
		pattern: [/\/flowplayer.*.js/i],
		name: "Flowplayer"
	},
	"howcast-videos": {
		pattern: [/howcast.com\/flash\/howcast_player.swf/i],
		name: "Howcast videos"
	},
	"js-three-3D": {
		pattern: [/\/Three.js/i, /"Three.js/i, /js:Three.js/i],
		name: "Three JS (3D)"
	},
	JWPlayer: {
		pattern: [/\/jwplayer.js/i],
		name: "JW Player"
	},
	"media-adobe-tv": {
		pattern: [/\/\/images.tv.adobe.com\/swf\/player.swf/i],
		name: "Adobe TV"
	},
	"media-blip-tv": {
		pattern: [/\/\/blip.tv\/play\//i],
		name: "Blip TV"
	},
	"videoplayer-kaltura": {
		pattern: [/kaltura_swf.addParam/i],
		name: "Kaltura Open Source Video Player"
	},
	"video-streaming-viddler": {
		pattern: [/viddler.com\/player\//i],
		name: "Viddler"
	},
	"videos-wistia": {
		pattern: [/\/\/embed.wistia.com\/deliveries\//i],
		name: "Wistia embedded videos"
	},
	"apache-flex": {
		pattern: [/Learn more about Flex at http:\/\/flex.org/i, /This application was built using Adobe Flex/i],
		name: "Apache Flex"
	},
	apple_touch: {
		pattern: [/<link rel="apple-touch-icon-precomposed"/i, /<link rel="apple-touch-icon"/i],
		name: "Apple Touch icons"
	},
	cdn_cloudfront: {
		pattern: [/.cloudfront.net\//i],
		name: "Amazon CloudFront (CDN)"
	},
	doxygen: {
		pattern: [/\x3c!-- Generated by Doxygen/i],
		name: "DoxyGen Documentation"
	},
	eventbrite: {
		pattern: [/\/\/www.eventbrite.com\/tickets-external/i],
		name: "Eventbrite"
	},
	github: {
		pattern: [/\/\/gist.github.com\/\d.*.js/i],
		name: "Github Gist"
	},
	gravatar: {
		pattern: [/\/\/s.gravatar.com\/js\/gprofiles.js/i],
		name: "Gravatars widget"
	},
	"html-signature": {
		pattern: [/\x3c!-- PAGE HAS HTML-SIGNATURE --\x3e/i],
		name: "HTML Signature"
	},
	"humans-txt": {
		pattern: [/\/humans.txt"/i],
		name: "Humans TXT"
	},
	jsfiddle: {
		pattern: [/\/\/jsfiddle.net\/.*\/embedded\/result/i],
		name: "jsFilddle"
	},
	"ms-bing": {
		pattern: [/<meta name="msvalidate.01" content="/i],
		name: "Bing Webmaster Tools"
	},
	surveymonkey: {
		pattern: [/<iframe src="http:\/\/www.surveymonkey.com\/s\//i],
		name: "Survey Monkey"
	},
	"syntax-highlighter": {
		pattern: [/\/SyntaxHighlighter\//i],
		name: "SyntaxHighlighter"
	},
	vertster: {
		pattern: [/.vertster.com\/" + Vswap.version + "\/vswap.js/i],
		name: "Vertster A/B Testing Software"
	},
	visualwebsiteoptimizer: {
		pattern: [/.visualwebsiteoptimizer.com\/deploy\/js_visitor_settings.php/i],
		name: "Visual Website Optimizer"
	},
	"w3c-html5-logo": {
		pattern: [/\/\/www.w3.org\/html\/logo\/badge\/html5-badge/i],
		name: "W3C HTML5 Logo Badge"
	},
	apple_iweb: {
		pattern: [/<meta name="Generator" content="iWeb /i],
		name: "Apple iWeb"
	},
	blog_tumblr: {
		pattern: [/\/tumblelog.js/i, /"http:\/\/assets.tumblr.com\//i, /<meta property="og:type" content="tumblr-feed:tumblelog" \/>/i],
		name: "Tumblr"
	},
	"blog-enki": {
		pattern: [/Powered by .*<a href="http:\/\/www.enkiblog.com".*>Enki/i],
		name: "Enki blog (Ruby on Rails)"
	},
	blogger: {
		pattern: [/<meta content=\'blogger\' name=\'generator/i],
		name: "blogger"
	},
	"blog-posterous-space": {
		pattern: [/<meta name="generator" content="Posterous/i],
		name: "Posterous Space Blog hosting"
	},
	"clan-sphere": {
		pattern: [/<meta name="generator" content="ClanSphere/i,
			/\/ClanSphere\//i],
		name: "ClanSphere"
	},
	"desk-com_support": {
		pattern: [/powered by Desk.com/i],
		name: "SalesForce Desk"
	},
	doc_sphinx: {
		pattern: [/Created using <a .*\?>Sphinx<\/a>/i, /<div class="sphinxsidebar">/i],
		name: "Sphinx Documentation"
	},
	jqtouch: {
		pattern: [/\/jqtouch-/i, /\/jqtouch-.*.js/i, /\/jqtouch.js/i],
		name: "jqTouch"
	},
	magento: {
		pattern: [/\/skin\/frontend\/base\/default\/js\/bundle.js/i, /var BLANK_URL = \'/i],
		name: "Magento"
	},
	"microsoft-sharepoint": {
		pattern: [/<meta name="GENERATOR" content="Microsoft SharePoint/i],
		name: "Microsoft SharePoint"
	},
	mootouch: {
		pattern: [/\/mootouch-/i, /\/mootouch-.*.js/i, /\/mootouch.js/i],
		name: "Mootouch"
	},
	"ms_asp.net": {
		pattern: [/<input type="hidden" name="__VIEWSTATE"/i, /SERVER INFO:.*X-Powered-By: ASP.NET/i],
		name: "ASP.Net Web Application Framework"
	},
	opencart: {
		pattern: [/\/index.php\?route=product\/product\//i, /OpenCart is open source software/i],
		name: "OpenCart Shopping Cart Solution"
	},
	pbworks: {
		pattern: [/\/\/vs1.pbworks.com/i],
		name: "PBworks - Online Team Collaboration"
	},
	"ruby-mephisto": {
		pattern: [/Powered by <a href="http:\/\/mephistoblog.com\/">/i],
		name: "Mephisto blog system (Ruby on Rails)"
	},
	"ruby-on-rails": {
		pattern: [/Powered by <a href="http:\/\/rubyonrails.com/i, /Powered by <a href="http:\/\/rubyonrails.org/i],
		name: "Ruby on Rails"
	},
	wiki_dokuwiki: {
		pattern: [/<meta name="generator" content="DokuWiki"\/>/i],
		name: "DokuWiki"
	},
	wiki_mediawiki: {
		pattern: [/<meta name="generator" content="MediaWiki (.*)"/i],
		name: "MediaWiki"
	},
	wiki_screwturn: {
		pattern: [/ScrewTurnWikiBCT/i],
		name: "ScrewTurn Wiki"
	},
	wpml: {
		pattern: [/<meta name="generator" content="WPML (.*)"/i],
		name: "WordPress Multilingual"
	},
	apple_quicktime: {
		pattern: [/http:\/\/www.apple.com\/library\/quicktime\/scripts\/ac_quicktime.js/i],
		name: "Apple Quicktime"
	},
	apple_quicktime_script: {
		pattern: [/http:\/\/www.apple.com\/library\/quicktime\/scripts\/qtp_library.js/i],
		name: "AC quicktime content scripts"
	},
	backbone: {
		pattern: [/\/backbone.js/i, /\/backbone-min.js/i, /\/backbone.ver.*.js/i],
		name: "Backbone JS script"
	},
	brighttag: {
		pattern: [/\/\/s.thebrighttag.com\/iframe/i],
		name: "BrightTag"
	},
	cufon: {
		pattern: [/\/cufon-yui.js/i,
			/cufon.set\(/i, /\/cufon-yui-.*.js/i, /cufon.js/i, /\/cufon\//i, /cufon-yui/i],
		name: "Cufon fonts"
	},
	disqus: {
		pattern: [/var disqus_domain = \'disqus.com\';/i, /<div id="disqus_thread"><\/div>/i],
		name: "Disqus comment"
	},
	dynamicdrive_dhtml: {
		pattern: [/\(c\) Dynamic Drive DHTML code library/i],
		name: "Dynamic Drive DHTML"
	},
	easyXDM: {
		pattern: [/easyXDM/i],
		name: "easyXDM"
	},
	"google-code-prettify": {
		pattern: [/prettyPrint();/i, /"prettify.js/i, /\/prettify.js/i],
		name: "Google Pretty Print"
	},
	"google-font": {
		pattern: [/\/\/fonts.googleapis.com/i],
		name: "Google fonts"
	},
	"infinite-scroll": {
		pattern: [/\/wp-infinite-scroll\/common.js/i, /jquery.infinitescroll/i],
		name: "Infinite Scroll"
	},
	jquery: {
		pattern: [/src="http:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/.*\/jquery.min.js/i, /\/jquery.min.js/i, /\/jquery-(.*).js/i, /\/jquery.js/i, /jquery.extend\(/i, /jquery()./i, /\/jquery\//i, /\$jq\(document\)/i],
		name: "jQuery"
	},
	js_dojo: {
		pattern: [/\/dojo\/dojo.xd.js/i, /\/dojo.js/i],
		name: "Dojo Toolkit 1.7"
	},
	js_headjs: {
		pattern: [/head.js\(/i],
		name: "Head JS"
	},
	js_raphael: {
		pattern: [/ Raphael\(/i,
			/js\/raphael.js"/i],
		name: "Raphael script"
	},
	"js-angular": {
		pattern: [/\/angular.min.js/i, /\/angular.js"/i, /\/angular-.*.min.js/i, /id="ng-app"/i, /data-ng-app/i],
		name: "Angular JS"
	},
	"js-qooxdoo": {
		pattern: [/\/qooxdoo(-.*|).js/i],
		name: "qooxdoo javascript framework"
	},
	"js-spine": {
		pattern: [/\/spine.js/i],
		name: "Spine JS"
	},
	kissinsights: {
		pattern: [/i.kissmetrics.com\/i.js/i],
		name: "Kiss insight"
	},
	modernizr: {
		pattern: [/modernizr.custom/i, /\/modernizr-/i, /\/modernizr.js/i, /\/modernizr.min.js/i],
		name: "Modernizr"
	},
	mollom: {
		pattern: [/\/mollom\//i],
		name: "Mollom"
	},
	mootools: {
		pattern: [/\/mootools-/i, /\/mootools-.*.js/i, /\/mootools.js/i, /\/mootools_all/i],
		name: "Mootools"
	},
	"mustache-js": {
		pattern: [/<script type="text\/mustache"/i],
		name: "mustache.js"
	},
	"nivo-slider": {
		pattern: [/\/wp-nivo-slider/i, /mod_nivoslider\//i],
		name: "Nivo Slider"
	},
	optimizely: {
		pattern: [/\/\/cdn.optimizely.com\/js\//i],
		name: "Optimizely: A/B testing software"
	},
	outbrain: {
		pattern: [/\/\/widgets.outbrain.com\/outbrain.js/i],
		name: "Outbrain"
	},
	pagepeeker: {
		pattern: [/http:\/\/pagepeeker.com\/thumbs.php/i],
		name: "Page Peeker"
	},
	recaptcha: {
		pattern: [/\/\/api.recaptcha.net\/js\//i, /\/\/www.google.com\/recaptcha\/api\/js\/recaptcha_ajax.js"/i, /\/\/www.google.com\/recaptcha\/api\/challenge/i],
		name: "reCAPTCHA"
	},
	script_dd_pngfix: {
		pattern: [/\/js\/pngfix.js/i, /DD_belatedPNG.fix/i],
		name: "DD_belatedPNG"
	},
	script_lowpro: {
		pattern: [/\/lowpro.js/i],
		name: "Low Pro : Prototype Scripts"
	},
	scriptaculous: {
		pattern: [/\/scriptaculous.js/i, /src="scriptaculous.js"/i, /\/scriptaculous\//i],
		name: "Scriptaculous script (Script.aculo.us)"
	},
	scrollback: {
		pattern: [/location.protocol+\'\/\/scrollback.io\'/i],
		name: "ScrollBack"
	},
	sifr: {
		pattern: [/sIFR.replaceElement/i, /sIFR 2.0.2/i],
		name: "sIFR Typography"
	},
	stats_prototype: {
		pattern: [/src="prototype.js"/i, /\/prototype.js"/i, /\/prototype.js/i, /\/prototype-.*.js/i],
		name: "prototype script"
	},
	"super-fish": {
		pattern: [/\/superfish_menu.js/i],
		name: "SuperFish menu script"
	},
	swfobject: {
		pattern: [/http:\/\/code.google.com\/p\/swfobject\//i, /\/swfobject.js/i, /\/swfobject-.*.js/i, /swfobject.embedSWF\(/i, /js\/swfobject.js"/i],
		name: "SWFObject (flash)"
	},
	typekit: {
		pattern: [/Typekit.load();/i, /\/\/use.typekit.com\//i],
		name: "TypeKit"
	},
	underscore: {
		pattern: [/\/underscore.js/i, /\/underscore-min.js/i, /\/underscore.ver.*.js/i],
		name: "Underscore JS script"
	},
	yahoo: {
		pattern: [/\/\/yui.yahooapis.com\//i, /\/yui_3.4.1.js/i],
		name: "Yahoo YUI"
	},
	zendesk: {
		pattern: [/\/inspectlet.js/i],
		name: "Zendesk"
	},
	"zepto-js": {
		pattern: [/\/zepto.js/i, /"zepto.js"/i],
		name: "Zepto.JS",
		js_obj: "window.$.zepto"
	},
	newrelic: {
		pattern: [/NREUMQ=NREUMQ\|\|\[\];NREUMQ.push/i],
		name: "New Relic - Performance Monitoring"
	},
	"parallels-PleskLin": {
		pattern: [/SERVER INFO:.*X-Powered-By: PleskLin/i],
		name: "Parallels Plesk Panel"
	},
	"parallels-PleskWindows": {
		pattern: [/SERVER INFO:.*X-Powered-By: PleskWin/i],
		name: "Parallels Plesk Panel (Windows)"
	},
	"ruby-phusion-passenger": {
		pattern: [/SERVER INFO:.*X-Powered-By: Phusion Passenger/i],
		name: "Phusion Passenger (mod_rails)"
	},
	"servers-apache": {
		pattern: [/SERVER INFO:.*Server: Apache/i],
		name: "Apache HTTP Server Project"
	},
	"servers-CentOS": {
		pattern: [/SERVER INFO:.*Server: .* \(CentOS\)/i],
		name: "CentOS"
	},
	"servers-google-front-end": {
		pattern: [/SERVER INFO:.*Server: Google Frontend/i, /SERVER INFO:.*Server: GWS/i, /SERVER INFO:.*Server: GFE/i, /SERVER INFO:.*Server: GSE/i],
		name: "Google Web Server (GFE)"
	},
	"servers-IIS": {
		pattern: [/SERVER INFO:.*Server: Microsoft-IIS\//i],
		name: "IIS Windows Server"
	},
	"servers-imb-httpserver": {
		pattern: [/SERVER INFO:.*Server: IBM_HTTP_Server/i],
		name: "IBM Web server"
	},
	"servers-litespeedtech": {
		pattern: [/SERVER INFO:.*Server: LiteSpeed/i],
		name: "LiteSpeed Server"
	},
	"servers-ngnix": {
		pattern: [/SERVER INFO:.*Server: nginx\//i, /SERVER INFO:.*Server: .*-nginx/i, /SERVER INFO:.*Server: nginx/i],
		name: "NGNix Server"
	},
	"servers-php": {
		pattern: [/SERVER INFO:.*X-Powered-By: PHP/i],
		name: "PHP - Hypertext Preprocessor"
	},
	"servers-servaxnet": {
		pattern: [/SERVER INFO:.*Server: ServaxNet/i],
		name: "ServaxNet server"
	},
	"servers-unix": {
		pattern: [/SERVER INFO:.*Server: .* \(Unix\)/i],
		name: "Unix server"
	},
	"servers-varnish": {
		pattern: [/SERVER INFO:.*Server: Varnish/i, /SERVER INFO:.*X-Varnish:/i],
		name: "Varnish Cache"
	},
	addthis: {
		pattern: [/.addthis.com\/js/i, /\/addthis_widget.js/i, /\x3c!-- AddThis Button BEGIN --\x3e/i, /\/\/.*.addthis.com\/js\//i],
		name: "AddThis bookmarker"
	},
	"addtoany-lockerz-share": {
		pattern: [/\/\/static.addtoany.com\/menu\/page.min.js/i],
		name: "AddToAny / Lockerz Share widget"
	},
	"animated-flying-twitter": {
		pattern: [/\/\/bloggerblogwidgets.googlecode.com\/files\/way2blogging.org-tripleflap.js/i],
		name: "Animated flying Twitter bird widget"
	},
	facebook: {
		pattern: [/\/\/www.facebook.com\/plugins\/like.php/i,
			/xmlns:fb="http:\/\/www.facebook.com\/2008\/fbml"/i, /\/\/www.facebook.com\/plugins\/likebox.php/i, /\/\/connect.facebook.net\/en_US\/all.js/i, /\/\/connect.facebook.net\/en_..\/all.js/i, /http:\/\/static.ak.fbcdn.net\/connect.php\/js\/FB.Share/i],
		name: "Facebook Social plugins"
	},
	"google-friend-connect": {
		pattern: [/\/\/www.google.com\/friendconnect\/script/i],
		name: "Google Friend Connect"
	},
	"google-plusone": {
		pattern: [/\/\/apis.google.com\/js\/plusone.js/i, /addthis_button_google_plusone/i, /<g:plusone /i, /"apis.google.com\/js\/plusone.js"/i],
		name: "Google Plus One"
	},
	linkedin: {
		pattern: [/\/\/platform.linkedin.com\/in.js/i, /\/\/www.linkedin.com\/img\/webpromo\//i],
		name: "LinkedIn plugins / sidebar widget"
	},
	sharethis: {
		pattern: [/\/\/w.sharethis.com\/widget\//i, /\/\/w.sharethis.com\/button\/buttons.js/i],
		name: "ShareThis widgets"
	},
	twitter: {
		pattern: [/\/\/platform.twitter.com\/widgets.js/i, /new TWTR.Widget\(/i, /\/\/platform.twitter.com\/anywhere.js/i],
		name: "Twitter plugins"
	},
	dreamweaver: {
		pattern: [/<META NAME="Generator" CONTENT="dreamweaver/i, /<META NAME="Generator" CONTENT="Dreamwaver/i,
			/function MM_preloadImages()/i],
		name: "Adobe Dreamweaver"
	},
	"microsoft-frontpage": {
		pattern: [/<meta name="GENERATOR" content="Microsoft FrontPage/i],
		name: "Microsoft FrontPage"
	},
	conversionruler: {
		pattern: [/\/\/www.conversionruler.com\/bin\/tracker.php/i],
		name: "ConversionRuler tracker"
	},
	extremetracking: {
		pattern: [/t1.extreme-dm.com\/i.gif/i],
		name: "Extreme tracking"
	},
	"google-analytics": {
		pattern: [/"google-analytics.com\/ga.min.js/i, /google-analytics.com\/ga.min.js/i, /\/\/www.google-analytics.com\/urchin.js/i,
			/_gaq.push\(\[\'_setAccount\'/i, /\x3c!-- Google Analytics Setup and Script --\x3e/i, /\/google-analytics-.*.js/i, /\[\'GoogleAnalyticsObject\'\]/i],
		name: "Google Analytics"
	},
	"hubspot-marketing": {
		pattern: [/var hs_ppa = ".*.app.*.hubspot.com"/i, /var hs_ppa = ".*.app.*.hubspot.com"/i, /\x3c!-- HubSpot Analytics for WordPress/i],
		name: "Hubspot tracker"
	},
	"marketo-marketing": {
		pattern: [/munchkin.marketo.net\/munchkin.js/i],
		name: "Marketo Marketing Software"
	},
	piwik: {
		pattern: [/Piwik.getTracker/i],
		name: "Piwik Stats"
	},
	quantcast: {
		pattern: [/"quantserve.com\/quant.js/i, /.quantserve.com\/quant.js/i, /http:\/\/edge.quantserve.com\/quant.js/i, /\x3c!-- Start Quantcast tag --\x3e/i],
		name: "Quantcast"
	},
	scorecardresearch: {
		pattern: [/\/\/b.scorecardresearch.com\/p/i, /.scorecardresearch.com\/beacon.js/i],
		name: "Scorecard Research"
	},
	sitecatalyst: {
		pattern: [/\/omniture_(.*).js/i, /\x3c!-- SiteCatalyst code/i, /\x3c!-- Begin SiteCatalyst code --\x3e/i, /\/Omniture.js/i, /.Omniture.loadScript();/i, /.2o7.net\//i, /\/omniture\/s_code.js/i,
			/.updateOmniture\(/i],
		name: "SiteCatalyst (omniture tracker)"
	},
	statcounter: {
		pattern: [/\/\/www.statcounter.com\/counter\/counter.js"/i, /"statcounter.com\/counter\/counter.js/i],
		name: "StatCounter"
	},
	stats_getclicky: {
		pattern: [/"http:\/\/static.getclicky.com\/js/i, /"\/\/static.getclicky.com\/js/i, /\/\/static.getclicky.com\'/i, /:\/\/in.getclicky.com\//i],
		name: "Clicky (GetClicky)"
	},
	"stats-alexa": {
		pattern: [/\/\/xslt.alexa.com\/site_stats\/js\//i],
		name: "Alexa Stats widgets"
	},
	"stats-amungus": {
		pattern: [/"http:\/\/whos.amung.us\//i,
			/\/\/widgets.amung.us\/tab.js/i, /\/\/widgets.amung.us\/colored.js/i, /\/\/widgets.amung.us\/small.js/i],
		name: "Amung us"
	},
	"stats-chartbeat": {
		pattern: [/static.chartbeat.com\/js\//i, /\x3c!-- Chartbeat --\x3e/i, /function loadChartbeat()/i],
		name: "Chartbeat"
	},
	"stats-clicktale": {
		pattern: [/\/\/s.clicktale.net\//i, /typeof ClickTale==\'function\'/i, /\/\/clicktalecdn.sslcs.cdngc.net/i],
		name: "ClickTale Tracker"
	},
	"stats-coremetrics": {
		pattern: [/\/\/libs.coremetrics.com\/eluminate.js/i],
		name: "Coremetrics Web Analytics"
	},
	"stats-flagcounter": {
		pattern: [/\/\/s\d\d.flagcounter.com\/count\//i],
		name: "FlagCounter"
	},
	"stats-gostats": {
		pattern: [/\/\/gostats.com\/go.js/i],
		name: "GoStats tracking"
	},
	"stats-mixpanel": {
		pattern: [/\/\/api.mixpanel.com\/site_media\/js\/api\/mixpanel.js/i],
		name: "Mixpanel | Mobile and Web Analytics"
	},
	"stats-opentracker": {
		pattern: [/\/\/script.opentracker.net\/\?site=/i],
		name: "Opentracker.net"
	},
	"stats-parsely": {
		pattern: [/\/\/static.parsely.com\/p.js/i],
		name: "Parse.ly Tracker"
	},
	"stats-reinvigorate": {
		pattern: [/\/\/include.reinvigorate.net\/re_.js/i],
		name: "Reinvigorate stats"
	},
	"stats-sitemeter": {
		pattern: [/sitemeter.com\/meter.asp/i, /sitemeter.com\/stats.asp/i],
		name: "Sitemeter"
	},
	"stats-tynt": {
		pattern: [/\/\/tcr.tynt.com\/javascripts\/Tracer.js/i, /\/javascript\/tynt.js/i],
		name: "Tynt Publisher Tools"
	},
	"stats-woopra": {
		pattern: [/\/\/static.woopra.com/i],
		name: "Woopra stats"
	},
	"stats-wordpress": {
		pattern: [/\/\/stats.wordpress.com\//i],
		name: "WordPress stats"
	},
	"stats-xiti": {
		pattern: [/xiti.com\/hit.xiti/i],
		name: "XiTi Tracker"
	},
	"yahoo-analytics": {
		pattern: [/\/\/ad.yieldmanager.com\/pixel/i,
			/YWA.getTracker/i],
		name: "Yahoo! Web Analytics tracking code"
	},
	"github-pages": {
		pattern: [/.github.io\//i],
		name: "GitHub Pages"
	},
	"google-developers": {
		pattern: [/\/\/ajax.googleapis.com\/ajax\/libs\//i],
		name: "Google Hosted Libraries (CDN)"
	},
	"rackspace-hosting-cdn": {
		pattern: [/\/\/.*.rackcdn.com\/dropdowncontent.js/i],
		name: "Rackspace CDN / Hosting"
	},
	"webhost-weebly": {
		pattern: [/\'weebly-footer\'/i, /.weebly-footer/i, /<meta property=\'og:url\' content=\'http:\/\/.*.weebly.com\/\' \/>/i, /\x3c!-- WEEBLY_START_CONTENT --\x3e/i,
			/SERVER INFO:.*Server: .*weebly.net/i],
		name: "Weebly"
	},
	"webs-com": {
		pattern: [/.webs.com\/"/i, /.webs.com"/i],
		name: "Webs"
	},
	"wordpress-com": {
		pattern: [/.wordpress.com\/xmlrpc.php"/i, /<meta name="generator" content="WordPress.com" \/>/i],
		name: "Wordpress.com blog"
	},
	"yola-synthasite": {
		pattern: [/\/\/analytics.yola.net\/tracking.js/i, /SERVER INFO:.*SynthaSite-ID:/i, /Your domain is pointing to Yola!/i],
		name: "SynthaSite / Yola"
	},
	"amazon-widgets": {
		pattern: [/.amazon.com\/widgets\//i],
		name: "Amazon widgets"
	},
	"bitcoins-currency": {
		pattern: [/href="bitcoin:/i],
		name: "Bitcoins links"
	},
	"brightcove-videos": {
		pattern: [/class="BrightcoveExperience"/i, /\/\/c.brightcove.com\/services\/viewer\//i],
		name: "Brightcove Videos"
	},
	chat: {
		pattern: [/\/\/www\d.cbox.ws\//i],
		name: "Cbox chat widget"
	},
	"chat-chatango": {
		pattern: [/.chatango.com\/group"/i],
		name: "Chatango chatboxes"
	},
	"chat-liveperson": {
		pattern: [/\/\/server.iad.liveperson.net\/hc\//i],
		name: "LivePerson chat"
	},
	"chat-olark": {
		pattern: [/"static.olark.com\/jsclient\//i, /\x3c!-- begin olark code --\x3e/i],
		name: "olark chat"
	},
	"civicuk-cookie-control": {
		pattern: [/\/cookieControl-/i],
		name: "Cookie Control widget"
	},
	cloudflare: {
		pattern: [/\/\/ajax.cloudflare.com\/cdn-cgi\//i],
		name: "CloudFlare"
	},
	"cloudflare-email-protection": {
		pattern: [/\/\/cloudflare.com\/email-protection.html/i, /cloudflare.com\/email-protection"/i],
		name: "CloudFlare Email Protection"
	},
	"codes-ohloh": {
		pattern: [/\/\/www.ohloh.net\/projects\/.*\/widgets\/project_thin_badge.gif/i],
		name: "Ohloh widget"
	},
	commentluv: {
		pattern: [/\/wp-content\/plugins\/commentluv\//i],
		name: "CommentLuv"
	},
	contactme_widgets: {
		pattern: [/\/\/static.contactme.com\/widgets\/tab\/v1\/tab.js/i],
		name: "ContactMe.com widget"
	},
	copyscape: {
		pattern: [/will be detected by Copyscape./i],
		name: "Copyscape"
	},
	"donate-chipin": {
		pattern: [/\/\/widget.chipin.com\/widget\//i],
		name: "Chipin donation/payment button"
	},
	"donate-flattr": {
		pattern: [/https:\/\/flattr.com\/submit\/auto/i],
		name: "Flattr Donate widget"
	},
	"donate-pledgie": {
		pattern: [/\/\/www.pledgie.com\/campaigns\/.*.png/i],
		name: "Pledgie - Donate widget"
	},
	"email-benchmark": {
		pattern: [/\/\/www.benchmarkemail.com\/code\/lbformnew.js/i],
		name: "Benchmark Email Marketing Services"
	},
	feedjit: {
		pattern: [/\/\/feedjit.com\/serve\//i],
		name: "FEEDJIT"
	},
	flickr: {
		pattern: [/\x3c!-- Start of Flickr Badge --\x3e/i],
		name: "Flickr Photos"
	},
	"getglue-widgets": {
		pattern: [/\/\/widgets.getglue.com\/checkin.js/i],
		name: "GetGlue widgets"
	},
	getsatisfaction: {
		pattern: [/amazonaws.com\/getsatisfaction.com\//i],
		name: "Get Satisfaction"
	},
	"google-calendar": {
		pattern: [/https:\/\/www.google.com\/calendar\/embed\?/i],
		name: "Google Calendar"
	},
	"google-charts": {
		pattern: [/google.visualization\./i],
		name: "Google Chart Tools"
	},
	"google-cse": {
		pattern: [/"http:\/\/www.google.com\/cse\/brand\?form=/i, /"http:\/\/www.google.com\/cse/i],
		name: "Google Custom Search"
	},
	"google-gadgets": {
		pattern: [/\/\/www.gmodules.com\/ig\/ifr\?/i],
		name: "Google Gadgets widgets"
	},
	"google-loader": {
		pattern: [/google.load\(/i],
		name: "Google Loader"
	},
	"google-translate": {
		pattern: [/\/\/translate.google.com\/translate_a\/element.js/i],
		name: "Google Translate"
	},
	helpden: {
		pattern: [/\/\/helpden.com\/client\/helpden.js/i],
		name: "HelpDen"
	},
	kampyle: {
		pattern: [/\/\/cf.kampyle.com\/buttons\//i, /kampyle.com\/feedback_form\//i],
		name: "Kampyle widgets"
	},
	kickstarter: {
		pattern: [/\/\/www.kickstarter.com\/projects\/.*\/widget\/video.html/i],
		name: "Kickstarter video widget"
	},
	meebo: {
		pattern: [/\/\/cim.meebo.com\/cim/i, /window.Meebo\|\|function/i],
		name: "Meebo bar"
	},
	networkedblogs: {
		pattern: [/networkedblogs.com\/getnetworkwidget/i],
		name: "NetworkedBlogs widget by Ninua"
	},
	opinionlab: {
		pattern: [/"http:\/\/img.icbdr.com\/images\/opinionlabs\//i],
		name: "OpinionLab"
	},
	panoramio: {
		pattern: [/\/\/www.panoramio.com\/wapi\/template\/photo.html/i],
		name: "Panoramio photo widget"
	},
	paypal: {
		pattern: [/\/\/www.paypal.com\/en_US\/i\/btn\/btn_donateCC_LG_global.gif/i, /id="donate_form" action="https:\/\/www.paypal.com\/cgi-bin\/webscr"/i, /\/btn_donateCC_LG.gif/i, /\/\/www.paypal.com\/en_US\/i\/btn\/x-click-but21.gif/i, /\/\/www.paypal.com\/en_US\/i\/btn\/btn_donateCC_LG.gif/i, /alt="Donate with PayPal"/i],
		name: "Paypal Donate"
	},
	"picasa-google": {
		pattern: [/\/\/picasaweb.google.com\/s\/c\/bin\/slideshow.swf/i],
		name: "Picasa Web Albums widgets"
	},
	pinterest: {
		pattern: [/\/\/assets.pinterest.com\/js\/pinit.js/i],
		name: 'Pinterest - "Pin It" Button widget'
	},
	podtrac: {
		pattern: [/\/\/player.podtrac.com\/player\/embed.js/i],
		name: "PodTrac podcast widgets"
	},
	polldaddy: {
		pattern: [/\/\/static.polldaddy.com\/p\//i],
		name: "Poll Daddy Survey"
	},
	pulsemaps: {
		pattern: [/pulsemaps.com\/widget.js/i],
		name: "Pulsemaps tracker widget"
	},
	repost_us_embed: {
		pattern: [/repost.us\/syndicate\/create/i],
		name: "Repost.Us Embed tool"
	},
	"ring-revenue": {
		pattern: [/ringrevenue.com\/\d\/integration.js/i],
		name: "RingRevenue"
	},
	"seo-prchecker": {
		pattern: [/\/\/pr.prchecker.info\/getpr.php/i],
		name: "PR Checker - PAGE RANK Checker"
	},
	skype: {
		pattern: [/\/\/download.skype.com\/share\/skypebuttons\/js\/skypeCheck.js/i, /\/\/download.skype.com\/share\/skypebuttons\/buttons\//i],
		name: "Skype Me Button (Chat widget)"
	},
	slideshare: {
		pattern: [/\/\/static.slidesharecdn.com\/swf\//i],
		name: "SlideShare PowerPoint widget"
	},
	smartling: {
		pattern: [/.smartling.com\/ls\/"/i],
		name: "Smartling - Language Translation"
	},
	snapengage: {
		pattern: [/\/\/www.snapengage.com"\)/i,
			/SnapABug.init\(/i, /\x3c!-- begin SnapEngage code --\x3e/i],
		name: "SnapEngage Live chat"
	},
	soundcloud: {
		pattern: [/\/\/player.soundcloud.com\/player.swf/i, /soundcloud.com\/player\//i],
		name: "SoundCloud"
	},
	spotify: {
		pattern: [/\/\/embed.spotify.com\//i],
		name: "Spotify - music widget"
	},
	streampad: {
		pattern: [/\/sp-player.js/i],
		name: "Streampad music widget"
	},
	"tripadvisor-tripwow": {
		pattern: [/travelpod.com\/bin\/tripwow\/flash\/tripwow.swf/i, /travelpod.com\x2Fbin\x2Ftripwow\x2Fflash\x2Ftripwow.swf/i],
		name: "TripWow widget by TripAdvisor"
	},
	userecho: {
		pattern: [/userecho.com\/js\/widget-/i, /<a class="logo" href="http:\/\/userecho.com.*"><img src="\/s\/img\/poweredby_ue.png"><\/a>/i],
		name: "User Echo chat widgets"
	},
	uservoice: {
		pattern: [/widget.uservoice.com\//i],
		name: "UserVoice"
	},
	vCita_widgets: {
		pattern: [/var vcUrl = "www.vcita.com"/i, /\/\/my.vcita.com\/2\/loader.js/i],
		name: "vCita"
	},
	"vimeo-videos": {
		pattern: [/\/\/player.vimeo.com\/video\//i],
		name: "Vimeo Videos"
	},
	"wepay-donations": {
		pattern: [/\/\/www.wepay.com\/donate\//i, /\/\/www.wepay.com\/button\/widgets/i],
		name: "WePay donate buttons"
	},
	wibiya: {
		pattern: [/.wibiya.com\/Toolbars\//i],
		name: "Wibiya Toolbar"
	},
	"wufoo-forms": {
		pattern: [/\/\/.*.wufoo.com\/forms\//i],
		name: "Wufoo Forms"
	},
	"yahoo-webplayer": {
		pattern: [/\/\/mediaplayer.yahoo.com\/js"/i, /\/\/webplayer.yahooapis.com\/player.js/i],
		name: "Yahoo! WebPlayer"
	},
	youtube: {
		pattern: [/\/\/www.youtube.com\/v\//i, /\/\/www.youtube.com\/embed/i],
		name: "Youtube videos"
	},
	"youtube-playlist": {
		pattern: [/\/\/www.youtube.com\/embed\/p\//i],
		name: "Youtube videos playlist"
	},
	"zopim-chat": {
		pattern: [/\/\/cdn.zopim.com\//i,
			/document.location.protocol.*\/\/zopim.com\//i],
		name: "Zopim live chat widget",
		js_obj: "window.$zopim"
	},
	"wp-twentyfourteen": {
		pattern: [/\/twentyfourteen\//i],
		name: "Twenty Fourteen"
	}
};
jQuery.extend(window, px_ptn);